### ISSUE TITLE
Setting Dynamic Page-Specific Meta Descriptions?

### ISSUE THREAD

**Issue by e-karma** [walter/ember-cli-meta-options#1]
Thanks for the contribution!

Can this addon provide this functionality?  If so how?

If not, do you know of a possible solution?

**Comment by walter** [comment]
On its own, this addon can't, but I do add dynamic meta tags when I use it.

I use it with a wrapping jQuery loader that sets the meta options.

https://github.com/opengovernment/askthem/blob/master/public/widgets/widget-builder/widget.js#L54-L91

I've written up a rough overview of a similar widget here:

http://discuss.emberjs.com/t/how-to-have-multiple-instances-of-an-app-in-same-window/6733/2

Hope that helps!

**Comment by walter** [comment]
Reopen if you have anymore questions.
