### ISSUE TITLE
Fix default related logic to be able to pass parentPathIgnoreUpTo=0

### ISSUE THREAD

**Issue by synaptiko** [walter/ember-cli-meta-options#2]
Hi,

I'm using your addon and I've noticed it's not possible to pass `parentPathIgnoreUpTo: 0`. It's because of this line: https://github.com/walter/ember-cli-meta-options/blob/master/app/initializers/options.js#L40

I found a workaround, I can just pass `'0'` instead of numeric 0 and it works. But I think it would be worth fixing directly. Just check `undefined` or `null` instead.

Thanks

**Comment by walter** [comment]
Wow! Good to hear that someone finds this useful. Been awhile since I looked at this. Any chance you could whip up your proposed changes as a PR?

**Comment by synaptiko** [comment]
@walter https://github.com/walter/ember-cli-meta-options/pull/3
